export const DEFAULT_OAUTH_CREDENTIAL_REF = 'YUANDIAN_MCP_OAUTH'
export const DEFAULT_OAUTH_AUTHORIZED_CREDENTIAL_REF = 'YUANDIAN_MCP_OAUTH_AUTHORIZED'
export const DEFAULT_API_KEY_CREDENTIAL_REF = 'YUANDIAN_API_KEY'
export const DEFAULT_OAUTH_START_CREDENTIAL_REF = 'YUANDIAN_MCP_OAUTH_START'
